//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dong_HDTT
    {
        public string SoHDTT { get; set; }
        public string MaXe { get; set; }
        public Nullable<System.DateTime> NgayNhanXe { get; set; }
        public Nullable<System.DateTime> NgayTraXe { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HoaDon_TTT HoaDon_TTT { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
