//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach
    {
        public Khach()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public string MaKhach { get; set; }
        public string TenKhach { get; set; }
        public string DiaChi { get; set; }
        public string CMTND { get; set; }
        public string SoDT { get; set; }
        public string SoTK { get; set; }
        public string NganHang { get; set; }
        public string TenCQ { get; set; }
    
        public virtual ICollection<HopDong> HopDongs { get; set; }
    }
}
