//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiXe
    {
        public LoaiXe()
        {
            this.ChiTietHopDongs = new HashSet<ChiTietHopDong>();
            this.DatXes = new HashSet<DatXe>();
            this.Gias = new HashSet<Gia>();
        }
    
        public string MaLoaiXe { get; set; }
        public string TenLoaiXe { get; set; }
        public Nullable<int> SoCho { get; set; }
        public Nullable<int> SoLuongXe { get; set; }
    
        public virtual ICollection<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual ICollection<DatXe> DatXes { get; set; }
        public virtual ICollection<Gia> Gias { get; set; }
    }
}
