//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThueXeOtoEntities : DbContext
    {
        public QuanLyThueXeOtoEntities()
            : base("name=QuanLyThueXeOtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual DbSet<DatXe> DatXes { get; set; }
        public virtual DbSet<Dong_HDTT> Dong_HDTT { get; set; }
        public virtual DbSet<Gia> Gias { get; set; }
        public virtual DbSet<HoaDon_TTT> HoaDon_TTT { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<Khach> Khaches { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<SoXe> SoXes { get; set; }
        public virtual DbSet<SuaChua> SuaChuas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<XeRa> XeRas { get; set; }
        public virtual DbSet<XeVao> XeVaos { get; set; }
    }
}
