//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThueXeOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        public Xe()
        {
            this.Dong_HDTT = new HashSet<Dong_HDTT>();
            this.SoXes = new HashSet<SoXe>();
            this.SuaChuas = new HashSet<SuaChua>();
            this.XeRas = new HashSet<XeRa>();
            this.XeVaos = new HashSet<XeVao>();
        }
    
        public string MaXe { get; set; }
        public string MaLoaiXe { get; set; }
        public string BienSo { get; set; }
        public string MoTa { get; set; }
        public string TinhTrang { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> GiaThue { get; set; }
    
        public virtual ICollection<Dong_HDTT> Dong_HDTT { get; set; }
        public virtual ICollection<SoXe> SoXes { get; set; }
        public virtual ICollection<SuaChua> SuaChuas { get; set; }
        public virtual ICollection<XeRa> XeRas { get; set; }
        public virtual ICollection<XeVao> XeVaos { get; set; }
    }
}
